In [2]:
import cv2
import numpy as np

# Cargar una imagen desde el archivo
imagen = cv2.imread('linux.jpg')

# Verifica si la imagen se ha cargado correctamente
if imagen is not None:
    # Convierte la imagen en una matriz NumPy
    matriz = np.array(imagen)
    
    # Ahora puedes trabajar con la matriz de la imagen
    print("Matriz de la imagen:")
    print(matriz)
else:
    print("No se pudo cargar la imagen.")


Matriz de la imagen:
[[[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 ...

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]]


In [5]:
cv2.imwrite('matriz_imagen.png', matriz)
cv2.imshow('Mi Imagen', matriz)
cv2.waitKey(0)
cv2.destroyAllWindows()