In [17]:
import cv2
import numpy as np
import json

# Cargar una imagen desde el archivo
imagen = cv2.imread('./img/alien_rojo.jpg')

# Verifica si la imagen se ha cargado correctamente
if imagen is not None:
    # Reducir la resolución de la imagen (por ejemplo, a 100x100 píxeles)
    imagen_reducida = cv2.resize(imagen, (100, 100))  # Ajusta el tamaño según sea necesario

    # Convierte la imagen reducida en una matriz NumPy
    matriz_reducida = np.array(imagen_reducida)

    # Convierte la matriz reducida a una lista de Python
    matriz_lista = matriz_reducida.tolist()

    # Define el nombre del archivo en el que deseas guardar la matriz en formato JSON
    nombre_archivo_json = "matriz_imagen_reducida.json"

    # Guardar la matriz en formato JSON
    with open(nombre_archivo_json, 'w') as archivo_json:
        json.dump(matriz_lista, archivo_json)

    print(f"La matriz de la imagen reducida se ha guardado en {nombre_archivo_json}")
else:
    print("No se pudo cargar la imagen.")


Matriz de la imagen:
[[[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 ...

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]

 [[40 40 40]
  [40 40 40]
  [40 40 40]
  ...
  [40 40 40]
  [40 40 40]
  [40 40 40]]]


TypeError: compress() missing required argument 'condition' (pos 1)